version: '3.4'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5023:5023"
    environment:
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=c:\\.nuget\\fallbackpackages2
      - NUGET_FALLBACK_PACKAGES=c:\\.nuget\\fallbackpackages;c:\\.nuget\\fallbackpackages2
    volumes:
      - "C:\\Users\\Ibeth Pacheco\\source\\repos\\HotelBookingSolutionProject\\HotelBookingSolution:C:\\app:rw"
      - "C:\\Users\\Ibeth Pacheco\\source\\repos\\HotelBookingSolutionProject\\HotelBookingSolution:c:\\src:rw"
      - "C:\\Users\\Ibeth Pacheco\\.nuget\\packages\\:c:\\.nuget\\fallbackpackages2:rw"
      - "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\NuGetPackages:c:\\.nuget\\fallbackpackages:rw"
