name: Push Checks

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Docker Compose
      run: |
        Invoke-WebRequest -Uri "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Windows-x86_64.exe" -OutFile "docker-compose.exe"
        Move-Item -Path "docker-compose.exe" -Destination "C:\Program Files\Docker\docker-compose.exe"

    - name: Add Docker Compose to PATH
      env:
        PATH: $PATH:C:\Program Files\Docker

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker

    - name: Log in to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/compose@v1
      with:
        file: docker-compose.yml
        command: build
      run: |
        docker-compose -f docker-compose.yml push

  deploy:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Docker Compose
      run: |
        Invoke-WebRequest -Uri "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Windows-x86_64.exe" -OutFile "docker-compose.exe"
        Move-Item -Path "docker-compose.exe" -Destination "C:\Program Files\Docker\docker-compose.exe"

    - name: Add Docker Compose to PATH
      env:
        PATH: $PATH:C:\Program Files\Docker

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: windows

    - name: Log in to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy to server
      uses: docker/compose@v1
      with:
        file: docker-compose.yml
        command: up -d